# ----
# Site

title: Hive Developer
description: Hive Developer Documentation.
baseurl: '/'
url: https://developers.hive.io
#google_analytics_key: UA-76480270-4
permalink: /:categories/:title.html

languages: ["en", "hi", "de", "fr", "ru", "zh"]
exclude_from_localizations: ["unused","tutorials","support","lib","js","images","css","_sass","_plugins","_layouts","_includes","_data"]


collections:
  introduction:
    title: Introduction
    id: introduction
    position: 1
    output: true
  contributors:
    title: Contributors
    id: contributors
    position: 2
    output: true
  quickstart:
    title: Quickstart
    id: quickstart
    position: 3
    output: true
  javascript:
    title: Javascript
    id: javascript
    position: 4
    output: true
  tutorials:
    title: Tutorials
    id: tutorials
    position: 5
    output: true
  services:
    title: Services
    id: services
    position: 6
    output: true
  layer2:
    title: Layer 2
    id: layer2
    position: 7
    output: true
  nodeop:
    title: Node Operation
    id: nodeop
    position: 8
    output: true
  resources:
    title: Resources
    id: resources
    position: 9
    output: true
  glossary:
    title: Glossary
    id: glossary
    position: 10
    output: true
  tutorials-recipes:
    title: Recipes
    id: tutorials-recipes
    position: 11
    output: true
  tutorials-javascript:
    title: Javascript Tutorials
    id: tutorials-javascript
    position: 12
    output: true
  tutorials-python:
    title: Python Tutorials
    id: tutorials-python
    position: 13
    output: true
  apidefinitions:
    title: API Definitions
    id: apidefinitions
    position: 14
    output: true
  testnet:
    title: Testnet
    id: testnet
    position: 15
    output: true
  tutorials-ruby:
    title: Ruby Tutorials
    id: tutorials-ruby
    position: 16
    output: true
  tutorials-php:
    title: Ruby Tutorials
    id: tutorials-php
    position: 17
    output: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-multiple-languages-plugin

exclude:
  - readme.md
  - LICENCE
  - vendor
  - Makefile
  - "tutorials"

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post

kramdown:
  auto_ids: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'CONTRIBUTING.md','tutorials']
